### PR TITLE
Python wrapper

### PR DESCRIPTION
**Pull request by ilyaraz**

### CODE REVIEW

**Comment by ludwigschmidt** [comment]
Should the wrapper allow input that is not aligned on 32-bytes? I'm not sure how easy it is to guarantee alignment with NumPy. One option could be an optional bool parameter allow_unaligned_input. If it is set to true (default is false), the wrapper copies the input to an aligned temporary array if necessary.

**Comment by ilyaraz** [comment]
Unfortunately, copying data back and forth is pretty expensive, so this implicit copying changes the running time pretty unpredictably. Let's just provide a function that creates an aligned NumPy array?

**Comment by ludwigschmidt** [comment]
Is creating an aligned NumPy array easy to do so it plays well with the garbage collector? If so, that sounds like a good approach.

I guess the ideal solution would be to make FFHT robust to mis-alignments: deal with the < 32 byte prefixes and suffices separately and use aligned AVX in the middle. It should only be a negligible running time overhead. But the code for this might be quite cumbersome to write.

**Comment by ilyaraz** [comment]
Well, we can do what you did in the function `aligned` at some point: first, create a bit larger array, and then declare a part of it to be a new one. Or you are saying this would doom the GC?

**Comment by ludwigschmidt** [comment]
The main point was that I don't know how the Python garbage collector interacts with memory allocated on the C++ side (we definitely don't want to create memory leaks by allocating memory ourselves).

I guess we could get around the issue of mis-aligned allocations on the C++ side by using the platform-specific allocation routines with guaranteed alignment?

**Comment by ilyaraz** [comment]
I'm not sure I follow you. What I suggested was to write a _Python_ function that, given `n` and `dtype`, creates a one-dimension array that is 32-bytes aligned. There is no need to use C for that (I think).

**Comment by ludwigschmidt** [comment]
Ah, OK. I was thinking about an approach on the C++ side. You are right that something similar to the `aligned` function we had a while ago should work and (hopefully) not lead to GC trouble.

**Comment by ilyaraz** [comment]
To me it looks like it is ready to be merged. Let me know if you are happy with the current version.

**Comment by ludwigschmidt** [comment]
Looks good to me. I guess the C and Python-wrapped timing results match?

Are we also pushing this to pypi?

**Comment by ilyaraz** [comment]
Yes, within several percent.

I can prepare a Pypi package, but in a bit, if that's OK.

**Comment by ludwigschmidt** [comment]
Sure, no need to hurry :-)

**Pull request merged**
