### PR TITLE
Support both Python 2.7 and Python 3.x

### PR DESCRIPTION
**Pull request by ahazxm**
Hi, I am trying to use this package to learn the [Practical and Optimal LSH for Angular Distance](https://arxiv.org/abs/1509.02897)(btw, I'm a big fan of u and Professor Alex Andoni), I find it only supports Python 2.
So 
- I write a Python wrapper so that FFHT can support Python 3.x (test env: anaconda + Python 2.7, 3.6, 3.7)
- Add some version detection code to make **example.py** to run correctly
- Delete the **ffht** fold because of an unknown error (both Python 2.7 and Python 3.x)
  - I rename the module name in **setup.py line:27** (_ffht -> ffht)

### CODE REVIEW

**Comment by ilyaraz** [comment]
@dnbaker I am far from the actual computer to test this. Does it look good for you?

**Comment by annemariet** [comment]
Hi! 
Any plans to merge this PR?
I just tested it within an anaconda environment with Python 3.6, it ran smoothly. I'm not familiar enough with the the code to tell whether it could have been done differently though.

**Comment by dnbaker** [comment]
Let me give this a whirl today. Thank you for the reminder!

**Comment by dnbaker** [comment]
I gave this a go, @ilyaraz.

I've tested this on both 2 and 3. Looks good to me.

**Pull request merged**
